[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
referral_contract = "4uL34WQ31gYhMjkks7bUd9yx2TYztvj2iUp9BjXvpnQg"

[programs.devnet]
referral_contract = "4uL34WQ31gYhMjkks7bUd9yx2TYztvj2iUp9BjXvpnQg"

[programs.mainnet]
referral_contract = "4uL34WQ31gYhMjkks7bUd9yx2TYztvj2iUp9BjXvpnQg"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://api.devnet.solana.com"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
